### ISSUE TITLE
Ex5: "Compiler"?

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#10]
Dans le README, l'exercice 5 est le seul qui a la précision "compiler", ce qui fait un peu étrange par rapport aux autres. Peut-être qu'on devrait tout simplement modifier le `run.sh` pour qu'il effectue lui-même la compilation ;)

**Comment by acadiou** [comment]
bah non.  c'était même la 1ere phrase du texte de l'exo 1. 

eux, le run.sh, est spécifié ici car il y a des variables d'entrée attendues. 

non pour faire le déroulé en automatique. il faut justement que chacun fasse les étapes. 

j'ai modofé de readme par ailleurs. 

... in progress mais je cls quand même ici.
