### ISSUE TITLE
exple_matmul_C : Pas de flags d'optimisation

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#11]
Il n'y a pas de flags d'optimisation dans le Makefile de cet exemple. Est-ce volontaire ?

Si le but est d'éviter que les fonctions soient inlinées, il y a d'autres manières d'y arriver. La manière la plus simple est de déplacer les fonctions dans un fichier C à part comme tu fais en Fortran, ça marche tant qu'il n'y a pas un petit malin comme moi pour activer la LTO. A défaut, on peut utiliser la directive de compilateur `__attribute__((noinline))`, qui est moins portable mais marche dans GCC et Clang.

**Comment by acadiou** [comment]
l'idée c'st que chacun essaie. j'ai mis le makefile pour avoir un squelette (un pense bête) et aller plus vite dans la construction des exécutale. mais rien n'oblique à prendre ce makefile.
