### ISSUE TITLE
exple_matmul_C: désynchronisation makefile exercice/solution

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#12]
Les makefiles de l'exercice et de la solution ne sont actuellement pas identiques. Je pense que pour éviter ce genre de synchronisation, il vaudrait mieux que le makefile de la solution soit un simple symlink de celui de l'exercice.

**Comment by acadiou** [comment]
dans mon idée, encore une fois le Makefile, c'est juste pour guider. Si ça induit en erreur, je le vire. 
surtout pas de link  : c'est pas gravé dans le marbre. 

si ok avec cette idée, je clos. sinon à réouvrir.

(merci pour ce scan rigoureux du dépôt)
