### ISSUE TITLE
exple_matsum_Fortran : Le fichier d'exercice contient une partie de la solution

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#15]
Le fichier `test.f90` et le `README.md` associés à `exple_matsum_Fortran` me semblent déjà contenir une bonne partie de la solution. Il faudrait la mettre à part comme tu as fait pour `exple_matmul_C`.

De plus, la solution donnée par le README.md de `exple_matsum_Fortran` semble moins complète que celle de `exple_matmul_C`. Il faudrait peut-être trouver un moyen de maintenir ces deux solutions plus synchrones, en extrayant les parties communes et faisant des symlinks judicieusement placés ?

**Comment by acadiou** [comment]
... pas de link si je suis le même fil rouge - 

mais euh c'est bien possible que ce ne soit pas propre. pas trop regardé le Fortran Dans ce dépôt. 

au début je me disais qu'il n'y avait pas besion de mettre la solution, mais après je me suis dit qu'il en fallait au moins 1, pour qu'au démarrage, si les participats ne sont pas autonomes, ils puissent commencer par celui qui a un corrigé.

je ne clos pas. je rajouterai un forme similaire de corrigé.

**Comment by acadiou** [comment]
modifié.
