### ISSUE TITLE
Exos LLNL: Droits de redistribution + Makefile

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#16]
Je ne sais pas trop si on a le droit de redistribuer les programmes du LLNL comme ça, ça vaudrait peut-être le coup d'envoyer un mot à l'auteur (il y a un mail en bas de page) juste pour vérifier qu'il est OK.

Ca pourrait être sympa d'ajouter un makefile à ces exercices-là aussi qui soit cohérent avec celui des autres. En fait, on pourrait envisager de mutualiser au maximum les makefiles entre les exercices de sorte que 1/on n'ait pas besoin de répercuter les modifs d'un makefile à un autre et 2/dans un deuxième temps, on puisse vérifier rapidement que tout compile juste en faisant un "make" dans la racine.

**Comment by acadiou** [comment]
j'ai mis le lien. vers les sources orginiales

pour moi, ces tuto sont bien faits en général. je voulais que ce soit présent pour qu'ils aillent aussi voir les autres s'ils en avaient besoin un jour.

à mettre dans leur biblio, quoi.
