### ISSUE TITLE
Ex4 : "Suivre les instructions du PDF"

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#17]
Le README recommande de suivre les instructions d'un PDF pour l'exercice 4, mais malheureusement ce PDF ne semble pas exister pour l'instant...

**Comment by acadiou** [comment]
voilà j'ai un peu fait le ménage. le pdf est extérieur au dépot des TP. pour l'instant je vois le dépôt comme une liste de codes à se mettre sous la dent. au cas où les participants n'en aient pas.
