### ISSUE TITLE
Faire des tests sur Poincaré

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#18]
Après ma relecture "à l'oeil" d'aujourd'hui, je pense essayer de faire les TPs sur Poincaré demain pour voir comment ça se passe.

Fais-moi signe si tu as déjà fait cette vérif' de ton côté ! :wink:

**Comment by acadiou** [comment]
non. j'ai pas demandé de compte sur Poincaré. 

par contre j'ai entendu que le système était ancien - du coup les benchs de la nasa, je les ai copiés car il faut modifier un peu le code s'il y a des vieux gcc (vers < 5)

mis en compilation conditionnelle.

tiens moi au courant des tests.

**Comment by HadrienG2** [comment]
Ayant des soucis avec Poincaré (rien qui devrait nous gêner le jour J, à première vue c'est juste un firewall chiant qu'on ne rencontre pas quand on se connecte de l'intérieur), j'ai commencé par des tests de TPs sur ma machine.

Je n'ai donc pas pu tester scorep/scalasca parce qu'il n'y a pas de paquet binaire pour ma distribution (openSUSE), et dans mon souvenir de la dernière fois que j'avais essayé de les compiler à la main c'est un niveau de galère incompatible avec le temps qui nous reste.

Sur les autres TPs, RAS pour le moment, comme tu le vois mes petites remarques sur github sont très mineures sur cette relecture.

J'occuperai le temps qui me reste à corriger des issues moi aussi + relire la conclusion que Bastien vient de m'envoyer, et je croise les doigts pour que Julien de l'IDRIS accepte de me laisser venir un peu en avance demain afin de faire un test de dernière minute sur Poincaré...

**Comment by acadiou** [comment]
ai l'accord de l'idris pour utiliser qq exos de leurs TPs pour du profiling sur les benchs NAS ne sont pas connus.

**Comment by HadrienG2** [comment]
Désolé, je n'ai pas tout compris dans la fin de la phrase sur les benchs NAS ^^'
