### ISSUE TITLE
Pas de symlink f95->gfortran sur ma machine, doit-on s'en inquiéter?

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#19]
Je suis en train de tester les TPs, sur ma machine parce que j'ai des soucis de connexion à Poincaré, et là je constate qu'il n'y a pas de symlink `f95` vers gfortran défini, ce qui fait planter la compilation de `exple_matsum_Fortran` via le Makefile (et aura sans doute le même effet pour les autres exemples Fortran).

A quel point ce symlink est-il standardisé sur les clusters? Peut-on partir du principe qu'il sera défini sur Poincaré ou faudra-t'il adapter?

**Comment by acadiou** [comment]
perso ca m'inquiète pas. ça se surabonde ds un make file. peut être que les gens préfèreront ifort. chacun modifiera, je crois.
