### ISSUE TITLE
E/S ?

### ISSUE THREAD

**Issue by acadiou** [acadiou/TP_Profiling#2]
@HadrienG2 

j'aimerai ton avis sur l'exo sur la mesure des E/S 

juste un essai de recherche aléatroire. 

faut il faire qqch plus proche des codes comme une lecture / écriture d'une matrice par exple ?

Anne

**Comment by HadrienG2** [comment]
Je pense qu'un exemple plus proche des codes de calcul serait sympa, car il permettrait de rester dans le thème et d'éviter que les gens se désintéressent de l'exemple à cause du côté artificiel. Une qualité de plusieurs de tes exemples, c'est qu'ils représentent des calculs qu'on voudrait vraiment faire.

AMHA, un bel exemple serait un solveur d'équa diff dépendante du temps qui écrit chaque pas de temps sur le disque. La présence de calcul peut induire les gens en erreur (et donc motiver l'utilisation d'outils), et on peut discuter des solutions (n'écrire que tous les N pas de temps). Mais je sais pas si on aura le temps, au pire tu peux peut-être recycler ton Poisson même si ce sera plus artificiel vu que le temps n'est pas une vraie variable.

**Comment by acadiou** [comment]
On 13/05/2019 14:52, Hadrien G. wrote:
> Je pense qu'un exemple plus proche des codes de calcul serait sympa, car
> il permettrait de rester dans le thème et d'éviter que les gens se
> désintéressent de l'exemple à cause du côté artificiel. Une qualité de
> plusieurs de tes exemples, c'est qu'ils représentent des calculs qu'on
> voudrait vraiment faire.
> 
> AMHA, un bel exemple serait un solveur simple (genre poisson) qui écrit
> chaque pas de temps sur le disque.

ok. je regarde mon vieux bench jacobi - en dernier recours

 La présence de calcul peut induire
> les gens en erreur (et donc motiver l'utilisation d'outils), et on peut
> discuter des solutions (n'écrire que tous les 100 pas de temps).

... mais on ne peut pas toujours décider comme ça :-) C'est la physique
qui décide !

**Comment by HadrienG2** [comment]
J'essaierai aussi de faire quelques démos de perf sur mon ordi portable vendredi, ça nous permettra de montrer les fonctionnalités qui nécessitent des permissions spéciales (ex: `perf timechart`, `perf record -a`, `perf top`...) ou une version récente de perf / du noyau Linux / des PMCs Intel.

**Comment by acadiou** [comment]
ok;

dans le pdf je mets la commande à utiliser pour modifier les permissions
(-1)

s'ils y en a qui l'insallent en local, ils pouront faire la manip

a+

**Comment by acadiou** [comment]
poisson ajouté.
