### ISSUE TITLE
Suggestion de ressource: tutoriel perf

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#24]
Je ne sais pas quelles ressources tu proposes de partager avec les participants sur perf, mais personnellement j'ai toujours eu du mal à trouver un tutoriel pour débutant qui me satisfasse sur cet outil, donc [j'en ai écrit un](https://twiki.cern.ch/twiki/bin/view/LHCb/CodeAnalysisTools#CPU_assisted_performance_analysi). Libre à toi de t'en inspirer ou pointer dessus.

(Techniquement parlant, ce tutoriel est sur une page de l'expérience CERN LHCb qui ne restera peut-être pas toujours publique et accessible à tous, mais je n'ai pas trouvé de meilleur hébergement pour l'instant. J'aviserai si le problème se présente.)

Une autre resource très précieuse sur cet outil, et tant d'autres choses dans le domaine de l'analyse de perfs Linux, est le site de mon seigneur et mentor [Brendan Gregg](http://www.brendangregg.com/). Plus particulièrement [sa page sur l'analyse de perfs Linux](http://www.brendangregg.com/linuxperf.html), et sa [sous-page sur l'outil perf en particulier](http://www.brendangregg.com/perf.html).

**Comment by acadiou** [comment]
ok. @HadrienG2  ajouter le lien dans le README du coup
