### ISSUE TITLE
memory

### ISSUE THREAD

**Issue by acadiou** [acadiou/TP_Profiling#3]
@HadrienG2 

je me demandais d'il fallait un test de suivi d'allocaton mémoire - et lequel pas exmpel ? 

allouer / désallour des tblx tpporaires ? sur zéro alogo ou sur 1 algo ?

**Comment by HadrienG2** [comment]
Hmmm... ça dépend si on veut présenter des outils qui font un suivi d'empreinte mémoire totale (en gros, qui sortent un plot RSS vs temps) ou des outils qui sont capables de faire un suivi à grain fin des allocations mémoires individuelles (ex: massif, modes "profiling heap" de jemalloc et tcmalloc).

Les second sont plus précis que les premiers, avec les avantages et inconvénients habituels:

- Plus facile d'interpréter le résultat et d'agir dessus
- Overhead de mesure plus importante
- Dépendent davantage d'un programmeur/compilateur coopératif (ex: utiliser un allocateur mémoire bien précis)
- Nécessitent généralement des symboles de debug

Si on part sur les seconds, on pourrait leur mettre comme exemple un programme avec une fuite mémoire, mais je ne suis pas sûr que ce soit le meilleur exemple car 1/c'est un peu éloigné de notre sujet de la performance et 2/il faut qu'on fasse attention à ne pas causer un "vrai" OOM sur l'hôte, car Linux sait très mal gérer ce genre de situation (en théorie il devrait juste tuer le programme, mais en pratique il a plutôt tendance à swapper ou freezer selon la configuration système).

**Comment by HadrienG2** [comment]
Bon, je sais pas trop si on a encore le temps de le faire pour cette édition, j'aurais tendance à dire -> v2.

**Comment by acadiou** [comment]
ajout suivi job memoire slurm. 

pour le reste v2 ok.
