### ISSUE TITLE
Niveau de détail énoncés

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#5]
Pour l'instant, les énoncés des exercices sont minimalistes. Je ne sais pas si c'est juste pour fixer les idées ou si c'est comme ça que tu envisages la version finale (style très autonome). Dans ce dernier cas, je pense qu'il faudrait quand même ajouter un minimum de doc sur les outils présentés pour les gens qui ne les ont jamais pratiqués. Ca peut aller d'un simple vers le manuel vers un guide d'utilisation spécialement conçu pour le TP, selon le temps qu'on peut y mettre...

**Comment by acadiou** [comment]
dans mon idée, l=es slides de 161 pages ne font que donner des exmple de comment il faut faire. 

ce projet TP_profile pour vendredi en tout cas, c'est histoire qu'ils aient des codes à se mettre sous la dent.  

on discuterait après d'en faire un 'TP' autonome, documenté etc. si toutefois l'expérience montre que ça sert à qqch.
