### ISSUE TITLE
Codes exple_timer_xxx non référencés par le README

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#6]
Puisque ces codes sont présents dans le dépôt, ce serait bien que le README fournisse une explication rapide de ce qu'ils font et pourquoi ils sont là.

**Comment by acadiou** [comment]
ben c'est du brouillon. on garde, on garde pas ?

**Comment by HadrienG2** [comment]
Bon, bah on dirait que tu les a enlevés finalement, donc...
