### ISSUE TITLE
Choix des outils de monitoring système

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#7]
Pour l'instant, dans les outils de monitoring système, on propose d'utiliser `top` et `htop`. L'avantage de ces outils est qu'ils seront présents ou faciles à installer sur à peu près toutes les machines, et qu'ils sont très connus donc il y a de bonnes chances que les gens les connaissent déjà ou puissent facilement trouver de l'aide à leur sujet. Mais je trouve qu'ils ont aussi quelques limitations gênantes, par exemple leur vision très fragmentaire des entrées-sorties.

Dans mon utilisation personnelle, j'adore `ksysguard` parce qu'il est très configurable et sait afficher plein de choses. Mais il a le défaut d'être une application GUI, et sur certains serveurs c'est pénible ou impossible d'en utiliser. Dans ces genre de cas, j'apprécie aussi `nmon` et `glances`. Le deuxième est plus joli, mais un peu lourd (il cause quelques % d'activité CPU à lui tout seul :() et il ne sait pas faire des graphes d'évolution au fil du temps (ce que fait `nmon` dans une certaine mesure).

Il faudra voir comment on veut gérer ce compromis entre "utiliser des outils standard disponibles partout" et "utiliser des outils plus puissants, mais plus exotiques".

**Comment by acadiou** [comment]
ok. je suis partie du ppe qu'on devait travailler sur lachine sans X11. 

tjs partante pour une démo par exemple, sur d'autres outils. les paricipants auront peut être leur favorit aussi de leur côté. 

à voir au fil de l'eau pdt le TP ?

**Comment by HadrienG2** [comment]
Ca me va, j'espère qu'il y en aura des sympas sur Poincaré ;) Sinon je ferai une démo sur ma bécane, comme pour perf.

**Comment by acadiou** [comment]
wait and see :-) !
