### ISSUE TITLE
Ex1 : "Mesurer le temps d'exécution avec [...] perf"

### ISSUE THREAD

**Issue by HadrienG2** [acadiou/TP_Profiling#9]
Dans l'exercice 1, je présume que tu voulais présenter `perf stat` aux gens. Peut-être que ça vaudrait le coup de préciser `perf stat` plutôt qu'un simple `perf`, car `perf` est une grosse boîte à outils en manque de tutos qui peut déstabiliser les nouveaux utilisateurs.

**Comment by acadiou** [comment]
oui, mais ici l'idée c'était un readme minimal. le reste est dans le cours (que certes tu n'as pas encore vu...).

ça va venir - reste plus que 30 mails.

:-) 

(merci en tt cas pour toutes res rq)
